Remove unused variables
This is most likely due to GCC v16's improvements:

  archival/lzop.c: In function 'lzo1x_optimize':
  archival/lzop.c:157:69: error: variable 'o_m3_b' set but not used [-Werror=unused-but-set-variable=]
    157 |         unsigned long o_m1_a = 0, o_m1_b = 0, o_m2 = 0, o_m3_a = 0, o_m3_b = 0;
        |                                                                     ^~~~~~
  archival/lzop.c:157:57: error: variable 'o_m3_a' set but not used [-Werror=unused-but-set-variable=]
    157 |         unsigned long o_m1_a = 0, o_m1_b = 0, o_m2 = 0, o_m3_a = 0, o_m3_b = 0;
        |                                                         ^~~~~~
  archival/lzop.c:157:47: error: variable 'o_m2' set but not used [-Werror=unused-but-set-variable=]
    157 |         unsigned long o_m1_a = 0, o_m1_b = 0, o_m2 = 0, o_m3_a = 0, o_m3_b = 0;
        |                                               ^~~~
  archival/lzop.c:157:35: error: variable 'o_m1_b' set but not used [-Werror=unused-but-set-variable=]
    157 |         unsigned long o_m1_a = 0, o_m1_b = 0, o_m2 = 0, o_m3_a = 0, o_m3_b = 0;
        |                                   ^~~~~~
  archival/lzop.c:157:23: error: variable 'o_m1_a' set but not used [-Werror=unused-but-set-variable=]
    157 |         unsigned long o_m1_a = 0, o_m1_b = 0, o_m2 = 0, o_m3_a = 0, o_m3_b = 0;
        |                       ^~~~~~

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>